#!/usr/bin/env node
/**
 * @zui.react/mcp — MCP server entry point.
 *
 * Speaks JSON-RPC 2.0 over stdio. On startup it loads the JSON registry
 * generated by scripts/build-mcp-registry.ts (~30 KB total) into memory,
 * then registers tools/resources/prompts with the official SDK.
 *
 * Cold start budget: <300 ms on a warm Node 20 process — no model calls,
 * no network, no parsing of TS source unless the user asks for it via a
 * resource template.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  GetPromptRequestSchema,
  ListPromptsRequestSchema,
  ListResourceTemplatesRequestSchema,
  ListResourcesRequestSchema,
  ListToolsRequestSchema,
  ReadResourceRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

import { tools, callTool } from './tools.js';
import { resources, resourceTemplates, readResource } from './resources.js';
import { prompts, getPrompt } from './prompts.js';
import { manifest } from './registry.js';

const server = new Server(
  {
    name: 'zui',
    version: manifest.zuiVersion,
  },
  {
    capabilities: {
      tools:     { listChanged: false },
      resources: { listChanged: false, subscribe: false },
      prompts:   { listChanged: false },
      logging:   {},
    },
    instructions: [
      `ZUI MCP server — exposes the @zui.react/zui design system to coding agents.`,
      ``,
      `Catalog: ${manifest.counts.components} components, ${manifest.counts.patterns} patterns,`,
      `${manifest.counts.effects} effects, ${manifest.counts.icons} brand icons.`,
      ``,
      `Use the *tools* for action + search:`,
      `  - list_components / list_patterns / list_effects / list_icons / list_groups`,
      `  - get_component / get_pattern / get_effect / get_icon / get_design_tokens`,
      `  - search                — unified BM25 search across the catalog`,
      `  - add_component / add_pattern    — return file-diff + dep update plan`,
      `  - scaffold_page         — full tsx page using one or more patterns`,
      ``,
      `Use the *resources* (zui:// URIs) when you want to attach context:`,
      `  zui://design-tokens   zui://component-api   zui://llms.txt`,
      `  zui://components/{name}/source   zui://patterns/{name}/source   zui://icons/{name}.svg`,
      ``,
      `Use the *prompts* (slash commands in Claude Code) for common workflows:`,
      `  /zui:add-component   /zui:scaffold-page   /zui:find-pattern`,
      `  /zui:apply-effect    /zui:design-system   /zui:component-deep-dive`,
      ``,
      `Always import from the single barrel:  import { Button, Card } from '@zui.react/zui';`,
      `Pair it with:                          import '@zui.react/zui/styles.css';`,
    ].join('\n'),
  }
);

/* ── Tools ─────────────────────────────────────────────────────────────── */

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools }));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  return callTool(req.params.name, (req.params.arguments ?? {}) as Record<string, unknown>);
});

/* ── Resources ─────────────────────────────────────────────────────────── */

server.setRequestHandler(ListResourcesRequestSchema, async () => ({
  resources,
}));

server.setRequestHandler(ListResourceTemplatesRequestSchema, async () => ({
  resourceTemplates,
}));

server.setRequestHandler(ReadResourceRequestSchema, async (req) => ({
  contents: await readResource(req.params.uri),
}));

/* ── Prompts ───────────────────────────────────────────────────────────── */

server.setRequestHandler(ListPromptsRequestSchema, async () => ({ prompts }));

server.setRequestHandler(GetPromptRequestSchema, async (req) =>
  getPrompt(req.params.name, (req.params.arguments ?? {}) as Record<string, string>)
);

/* ── Bootstrap ─────────────────────────────────────────────────────────── */

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  // Servers are expected to be silent on stdout (the transport owns it).
  // Logs go to stderr so `claude mcp` can show them when debugging.
  process.stderr.write(
    `[zui-mcp] connected — zui ${manifest.zuiVersion}, ` +
      `${manifest.counts.components}c / ${manifest.counts.patterns}p / ` +
      `${manifest.counts.effects}e / ${manifest.counts.icons}i\n`
  );
}

main().catch((err) => {
  process.stderr.write(`[zui-mcp] fatal: ${(err as Error).stack ?? err}\n`);
  process.exit(1);
});
